=begin
#IronFunctions

#null

OpenAPI spec version: 0.0.3

Generated by: https://github.com/swagger-api/swagger-codegen.git

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

=end

require 'spec_helper'
require 'json'

# Unit tests for IronFunctions::AppsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'AppsApi' do
  before do
    # run before each test
    @instance = IronFunctions::AppsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AppsApi' do
    it 'should create an instact of AppsApi' do
      expect(@instance).to be_instance_of(IronFunctions::AppsApi)
    end
  end

  # unit tests for apps_app_get
  # Get information for a app.
  # This gives more details about a app, such as statistics.
  # @param app name of the app.
  # @param [Hash] opts the optional parameters
  # @return [AppWrapper]
  describe 'apps_app_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for apps_app_put
  # Create/update a app.
  # You can set app level settings here. 
  # @param app name of the app.
  # @param body App to post.
  # @param [Hash] opts the optional parameters
  # @return [AppWrapper]
  describe 'apps_app_put test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for apps_get
  # Get all app names.
  # Get a list of all the apps in the system.
  # @param [Hash] opts the optional parameters
  # @return [AppsWrapper]
  describe 'apps_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for apps_post
  # Post new app
  # Insert a new app
  # @param body App to post.
  # @param [Hash] opts the optional parameters
  # @return [AppWrapper]
  describe 'apps_post test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
