=begin
#IronFunctions

#The open source serverless platform.

OpenAPI spec version: 0.1.29

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.2.3

=end

require 'spec_helper'
require 'json'

# Unit tests for IronFunctions::RoutesApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'RoutesApi' do
  before do
    # run before each test
    @instance = IronFunctions::RoutesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of RoutesApi' do
    it 'should create an instance of RoutesApi' do
      expect(@instance).to be_instance_of(IronFunctions::RoutesApi)
    end
  end

  # unit tests for apps_app_routes_get
  # Get route list by app name.
  # This will list routes for a particular app.
  # @param app Name of app for this set of routes.
  # @param [Hash] opts the optional parameters
  # @return [RoutesWrapper]
  describe 'apps_app_routes_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for apps_app_routes_post
  # Create new Route
  # Create a new route in an app, if app doesn&#39;t exists, it creates the app
  # @param app name of the app.
  # @param body One route to post.
  # @param [Hash] opts the optional parameters
  # @return [RouteWrapper]
  describe 'apps_app_routes_post test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for apps_app_routes_route_delete
  # Deletes the route
  # Deletes the route.
  # @param app Name of app for this set of routes.
  # @param route Route name
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'apps_app_routes_route_delete test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for apps_app_routes_route_get
  # Gets route by name
  # Gets a route by name.
  # @param app Name of app for this set of routes.
  # @param route Route name
  # @param [Hash] opts the optional parameters
  # @return [RouteWrapper]
  describe 'apps_app_routes_route_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for apps_app_routes_route_patch
  # Update a Route
  # Update a route
  # @param app name of the app.
  # @param route route path.
  # @param body One route to post.
  # @param [Hash] opts the optional parameters
  # @return [RouteWrapper]
  describe 'apps_app_routes_route_patch test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
